# server:
#   port: 8080
#   tomcat:
#     max-http-form-post-size: 1048576000

# spring:
#   application:
#     name: BE

#   datasource:
#     driver-class-name: com.mysql.cj.jdbc.Driver
#     username: root
#     password: 123456
#     url: jdbc:mysql://localhost:3306/lakeSide_hotel_db

#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties:
#       format-sql: true
#       hibernate:
#         sql: true
#         dialect: org.hibernate.dialect.MySQLDialect

#   servlet:
#     multipart:
#       enabled: true
#       max-file-size: 1024MB
#       max-request-size: 1024MB
#       file-size-threshold: 1024MB

# logging:
#   level:
#     "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
# # App Properties

